name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test to test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Clean
      run: xcodebuild clean -project GitActionProject.xcodeproj -scheme GitActionProject
    - name: Run Testing
      run: xcodebuild test -project GitActionProject.xcodeproj -scheme GitActionProject -destination 'platform=iOS Simulator,name=iPhone 11'
    - name: Run Build
      run: xcodebuild build -project GitActionProject.xcodeproj -scheme GitActionProject
    
