name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test to test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean -workspace GitActionProject.xcworkspace -configuration Release -scheme GitActionProject
    - name: Run tests
      run: swift test -v
